name: append_uri_component
description: Append a component to a Dart `Uri`.
version: 1.1.0
homepage: https://github.com/flutter-cavalry/append_uri_component

environment:
  sdk: ">=2.18.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
